# Capítulo III: Requirements Specification

## 3.1. User Stories.


#### Épicas
| Epic / Story ID | Título | Descripción | Criterios de Aceptación | Relacionado con (Epic ID) |
|-----------------|--------|-------------|--------------------------|--------------------------|
| EPIC 001 | Landing Page |Como visitante, quiero acceder a una landing page con contenido diferenciado para personas ocupadas y aficionados, para identificar rápidamente cómo el producto se adapta a mi perfil específico.|**Escenario 01: Contenido para personas ocupadas**<br>- Dado que un visitante del segmento "personas ocupadas" accede al sitio<br>- Cuando navega por las secciones<br>- Entonces encuentra casos de uso sobre automatización y ahorro de tiempo<br>- Y ve testimonios de usuarios con perfiles similares al suyo <br> **Escenario 02: Contenido para aficionados**<br>- Dado que un visitante del segmento "aficionados" explora el sitio<br>- Cuando revisa las funcionalidades<br>- Entonces encuentra información sobre herramientas avanzadas y análisis de datos<br>- Y ve ejemplos de diagnósticos detallados y seguimiento histórico <br>	**Reglas de Negocio:**<br>- La landing page debe cargar completamente en menos de 3 segundos en conexión 4G<br>- El contenido debe estar disponible en español e inglés<br>- Los testimonios deben ser de usuarios reales verificados<br>- Los CTAs deben ser visibles sin necesidad de scroll en viewport móvil|N/A|
| EPIC 002 | Autenticación y Seguridad |Como usuario, quiero registrarme e iniciar sesión de forma segura, para proteger mis datos personales y el historial de mis plantas. |**Escenario 01: Registro seguro**<br>- Dado que un visitante se registra en la plataforma<br>- Cuando proporciona email válido y contraseña segura<br>- Entonces recibe confirmación por correo electrónico<br>- Y sus credenciales se almacenan de forma encriptada<br>**Escenario 02: Inicio de sesión confiable**<br>- Dado que un usuario registrado intenta acceder<br>- Cuando ingresa credenciales correctas<br>- Entonces el sistema autentica y redirige a su dashboard<br>- Y la sesión se mantiene segura durante la navegación **Reglas de Seguridad:**<br>- Las contraseñas deben tener mínimo 8 caracteres con al menos 1 mayúscula, 1 número y 1 carácter especial<br>- Los tokens de sesión expiran después de 24 horas de inactividad<br>- Máximo 5 intentos de login fallidos antes de bloqueo temporal por 30 minutos<br>- Todos los datos sensibles deben encriptarse en tránsito y en reposo|N/A|
| EPIC 003 | Gestión Básica de Plantas |Como usuario, quiero registrar y administrar mis plantas de manera sencilla, para tener un control centralizado de todas mis plantas en un solo lugar. |**Escenario 01: Registro simplificado**<br>- Dado que un usuario quiere agregar una nueva planta<br>- Cuando completa información básica (nombre, especie, ubicación)<br>- Entonces la planta queda registrada en su dashboard<br>- Y el proceso se completa en menos de 2 minutos<br>**Escenario 02: Visualización unificada**<br>- Dado que un usuario tiene múltiples plantas registradas<br>- Cuando accede a su dashboard principal<br>- Entonces ve todas sus plantas con estado actual de salud<br>- Y puede identificar rápidamente las que necesitan atención<br>**Reglas de Límites:**<br>- Usuarios gratuitos pueden registrar hasta 5 plantas<br>- Usuarios premium pueden registrar hasta 50 plantas<br>- El nombre de planta no puede exceder 50 caracteres<br>- No se permiten caracteres especiales en nombres de plantas excepto guiones|N/A|
| EPIC 004 | Monitoreo Automatizado para Personas Ocupadas |Como persona ocupada, quiero que el sistema monitoree automáticamente mis plantas y me notifique solo cuando sea estrictamente necesario, para liberarme de la carga mental de recordar constantemente su cuidado.|**Escenario 01: Notificación proactiva**<br>- Dado que una planta alcanza umbral crítico de humedad<br>- Cuando el sistema detecta la necesidad urgente<br>- Entonces envía una notificación push directa y clara<br>- Y el usuario no necesita revisar la app constantemente<br>**Escenario 02: Modo silencioso**<br>- Dado que todas las plantas están en estado óptimo<br>- Cuando el usuario revisa la aplicación<br>- Entonces ve un estado "Todo en orden"<br>- Y no recibe notificaciones innecesarias<br>**Reglas de Notificaciones:**<br>- No se envían notificaciones entre 10 PM y 7 AM hora local del usuario<br>- Máximo 3 notificaciones por día para usuarios del plan básico<br>- Las notificaciones críticas ignoran el modo silencioso del dispositivo<br>- Se requiere confirmación de lectura para notificaciones críticas|N/A|
| EPIC 005 | Herramientas Avanzadas para Aficionados |Como aficionado a las plantas, quiero acceder a diagnósticos detallados, historiales extensos y recomendaciones personalizadas, para profundizar en mi conocimiento y optimizar el cuidado basado en datos.|**Escenario 01: Diagnóstico detallado**<br>- Dado que una planta muestra signos de estrés<br>- Cuando el usuario consulta el diagnóstico avanzado<br>- Entonces recibe información sobre posibles causas (exceso de agua, falta de luz, etc.)<br>- Y ve soluciones específicas recomendadas<br>**Escenario 02: Historial completo**<br>- Dado que un usuario quiere analizar tendencias<br>- Cuando accede al historial de una planta<br>- Entonces visualiza gráficos de evolución de humedad, temperatura y luz<br>- Y puede comparar con períodos anteriores<br>**Reglas de Acceso:**<br>- Los diagnósticos avanzados requieren suscripción premium<br>- El historial se retiene por 24 meses para usuarios premium, 3 meses para básicos<br>- Los reportes PDF no pueden exceder 10MB de tamaño<br>- Los datos de exportación incluyen solo información del usuario, no de la comunidad|N/A|
| EPIC 006 | Comunidad y Colaboración entre Usuarios |Como usuario, quiero participar en una comunidad donde pueda compartir experiencias, recibir consejos de otros cuidadores y colaborar en el cuidado de plantas, para enriquecer mi conocimiento y sentirme parte de una red de apoyo. |**Escenario 01: Experiencia comunitaria integrada**<br>- Dado que un usuario completa el registro básico<br>- Cuando accede por primera vez a la comunidad<br>- Entonces encuentra contenido relevante según sus tipos de plantas<br>- Y puede interactuar inmediatamente con otros usuarios afines**Escenario 02: Valor educativo continuo**<br>- Dado que un usuario participa regularmente en la comunidad<br>- Cuando comparte y recibe feedback<br>- Entonces acumula conocimiento aplicable a sus plantas<br>- Y mejora progresivamente sus técnicas de cuidado<br>**Reglas de Comunidad:**<br>- Usuarios nuevos no pueden publicar enlaces externos hasta tener 10 reputación<br>- Las fotos compartidas no pueden exceder 5MB ni contener metadatos de ubicación<br>- El contenido se modera automáticamente con lista de palabras prohibidas<br>- Usuarios pueden reportar contenido, con 3 reportes se suspende publicación automáticamente    | N/A|
| EPIC 007 | Alertas Inteligentes Contextuales|Como usuario, quiero recibir alertas contextuales que me indiquen no solo el problema sino también causas posibles y soluciones, para tomar acciones informadas rápidamente.|**Escenario 01: Alerta con diagnóstico**<br>- Dado que la humedad del suelo baja críticamente<br>- Cuando se genera la alerta<br>- Entonces incluye posible causa (temperatura alta, suelo muy drenante, maceta pequeña)<br>- Y sugiere acciones específicas (regar inmediatamente, mover a sombra, transplantar)<br>**Escenario 02: Alertas preventivas**<br>- Dado que una planta muestra tendencia descendente en salud<br>- Cuando el sistema detecta patrón de deterioro<br>- Entonces envía alerta preventiva antes de llegar a estado crítico<br>- Y recomienda acciones correctivas tempranas<br>**Reglas de Alertas:**<br>- Las alertas preventivas requieren tendencia consistente de 72 horas<br>- El diagnóstico automático considera máximo 3 causas probables por alerta<br>- Las soluciones sugeridas deben estar validadas por al menos 10 casos exitosos en la comunidad<br>- No se generan alertas por fluctuaciones menores al 5% en rangos normales|N/A|
| EPIC 008 | Configuración Inteligente de Dispositivos|Como usuario, quiero vincular y configurar fácilmente mis sensores IoT con perfiles predefinidos según mi tipo de planta y ubicación, para que el dispositivo comience a monitorear automáticamente sin necesidad de configuración técnica compleja.|**Escenario 01: Vinculación simplificada**<br>- Dado que un usuario adquiere un nuevo sensor<br>- Cuando escanea el código QR del dispositivo<br>- Entonces el sistema lo detecta automáticamente<br>- Y guía al usuario en asignarlo a una planta específica<br>**Escenario 02: Configuración automática por tipo de planta**<br>- Dado que un usuario selecciona "Suculenta" al registrar planta<br>- Cuando vincula el sensor<br>- Entonces el sistema aplica automáticamente umbrales de humedad para suculentas<br>- Y configura frecuencias de monitoreo adecuadas<br>**Reglas de Dispositivos:**<br>- Máximo 3 dispositivos por usuario en plan básico, ilimitado en premium<br>- Los dispositivos deben recertificar conexión cada 24 horas<br>- La batería crítica se define como menor al 15% de capacidad<br>- Los datos de sensores se muestran con precisión de ±2% para humedad, ±0.5°C para temperatura|N/A| 
| EPIC 009 | Gestión de suscripciones|Como usuario, quiero elegir entre diferentes modelos de pago (compra única de hardware o suscripción mensual con servicios premium) según mis necesidades y presupuesto, para acceder a las funcionalidades que más valoro.|**Escenario 01: Opción de compra única**<br>- Dado que un usuario prefiere pago único<br>- Cuando selecciona el plan básico<br>- Entonces accede a funciones esenciales de monitoreo<br>- Y no tiene compromisos de pago recurrentes<br>**Escenario 02: Suscripción premium**<br>- Dado que un usuario quiere funcionalidades avanzadas<br>- Cuando elige suscripción mensual<br>- Entonces desbloquea diagnósticos avanzados, historiales extensos e integración con clima<br>- Y puede cancelar en cualquier momento<br>**Reglas de Facturación:**<br>- Las suscripciones se renuevan automáticamente 24 horas antes del vencimiento<br>- Período de gracia de 7 días para pagos fallidos antes de suspensión<br>- Reembolsos completos dentro de primeros 14 días de suscripción<br>- Los cambios de plan premium a básico mantienen funciones hasta fin de período pagado|N/A|
#### Historias de usuario
| Epic / Story ID | Título | Descripción | Criterios de Aceptación | Relacionado con (Epic ID) |
|-----------------|--------|-------------|--------------------------|--------------------------|
|US-001|Acceso a la Landing Page|Como visitante, quiero acceder a una landing page optimizada desde cualquier dispositivo, para conocer rápidamente los beneficios del producto y cómo se adapta a diferentes tipos de usuarios.  |<br>**Escenario 01: Acceso correcto**<br>- Dado que un visitante accede a la URL de la aplicación<br>- Cuando carga la página desde un navegador compatible<br>- Entonces la landing page se muestra correctamente<br>- Y el contenido principal es visible en menos de 3 segundos<br>**Escenario 02: Responsividad**<br>- Dado que un visitante accede desde un dispositivo móvil<br>- Cuando carga la landing page<br>- Entonces la página se adapta al tamaño de pantalla<br>- Y los elementos principales son accesibles sin perder funcionalidad <br>**Reglas de negocio:**<br>- La página debe ser accesible desde cualquier dispositivo con conexión a internet y navegador compatible con HTML5.<br>- El tiempo de carga del contenido principal no debe superar los 3 segundos en conexiones estándar (4G o fibra).|EPIC 001|
|US-002|Secciones informativas diferenciadas|Como visitante, quiero ver secciones que muestren cómo el producto beneficia tanto a personas ocupadas como a aficionados, para identificar cómo se adapta a mis necesidades específicas.|**Escenario 01: Beneficios para personas ocupadas**<br>- Dado que un visitante explora la landing page<br>- Cuando revisa las secciones informativas<br>- Entonces encuentra contenido sobre automatización y ahorro de tiempo<br>- Y ve cómo el sistema libera la carga mental del cuidado constante<br>Escenario 02: Beneficios para aficionados<br>- Dado que un visitante con interés en datos accede al sitio<br>- Cuando navega por las funcionalidades<br>- Entonces encuentra información sobre herramientas avanzadas y análisis detallados<br>- Y comprende cómo puede optimizar sus cuidados basado en datos|EPIC-001|
|US-003|Call to Action contextual|Como visitante, quiero encontrar botones de acción claros y contextualizados según mis intereses, para iniciar mi relación con el producto de manera sencilla.|**Escenario 01: CTA para registro**<br>- Dado que un visitante decide registrarse<br>- Cuando hace clic en "Comenzar ahora" o "Registrarse"<br>- Entonces es redirigido al formulario de registro<br>- Y la transición ocurre sin errores ni demoras<br>**Escenario 02: CTA para más información**<br>- Dado que un visitante quiere conocer más detalles<br>- Cuando selecciona "Ver planes" o "Conocer funcionalidades"<br>- Entonces accede a secciones específicas con información detallada<br>- Y puede comparar opciones según sus necesidades<br>**Reglas de negocio:**<br>-Todos los botones de acción deben redirigir a rutas válidas dentro del ecosistema del producto (registro, planes, información).<br>- Las llamadas a la acción deben mantenerse visibles en todas las resoluciones (no ocultarse en móviles).|EPIC-001|
|US-004|Testimonios segmentados|Como visitante, quiero ver testimonios de usuarios reales que representen diferentes perfiles (ocupados y aficionados), para confiar en que el producto funciona para casos similares al mío.|**Escenario 01: Testimonios diversos**<br>- Dado que un visitante revisa la sección de testimonios<br>- Cuando explora las experiencias compartidas<br>- Entonces encuentra casos de personas ocupadas que resolvieron problemas de olvido<br>- Y también casos de aficionados que mejoraron sus técnicas de cuidado<br>**Escenario 02: Credibilidad de testimonios**<br>- Dado que un visitante evalúa la confiabilidad del producto<br>- Cuando revisa los testimonios<br>- Entonces cada testimonio incluye nombre y contexto de uso real<br>- Y las imágenes refuerzan la autenticidad de las experiencias<br>**Reglas de negocio:**<br>-Los testimonios deben corresponder a usuarios reales y verificados del producto.<br>- Cada testimonio debe incluir al menos el nombre y contexto del usuario.<br>- Las imágenes asociadas no pueden vulnerar la privacidad ni contener información sensible.|EPIC-001|
|US-005|Registro de usuario|Como visitante, quiero registrarme con datos básicos protegidos, para crear una cuenta segura que salvaguarde mi información personal y el historial de mis plantas.|**Escenario 01: Registro exitoso con validación**<br>- Dado que un visitante accede al formulario de registro<br>- Cuando completa nombre, email válido y contraseña segura<br>- Entonces el sistema crea la cuenta y envía confirmación por email<br>- Y las credenciales se almacenan de forma encriptada<br>**Escenario 02: Protección contra datos inválidos**<br>- Dado que un visitante ingresa email inválido o contraseña débil<br>- Cuando intenta registrarse<br>- Entonces el sistema muestra mensajes de error específicos<br>- Y no permite el registro hasta corregir los problemas de seguridad<br>**Reglas de negocio:**<br>-Cada usuario debe registrarse con un correo electrónico único y verificado.<br>- Las contraseñas deben cumplir políticas mínimas de seguridad (mínimo 8 caracteres, mayúsculas, minúsculas, número y símbolo).<br>- El sistema debe encriptar las contraseñas antes de almacenarlas.|EPIC-002|
|US-006|Inicio de sesión|Como usuario registrado, quiero autenticarme de forma segura con mis credenciales, para acceder de manera protegida a mis plantas y dispositivos.|**Escenario 01: Autenticación exitosa**<br>- Dado que un usuario registrado ingresa credenciales válidas<br>- Cuando el sistema verifica la identidad<br>- Entonces se concede acceso al dashboard principal<br>- Y se establece una sesión segura con token de autenticación<br>**Escenario 02: Protección contra acceso no autorizado**<br>- Dado que un usuario ingresa credenciales incorrectas<br>- Cuando el sistema detecta el error<br>- Entonces muestra mensaje genérico "Credenciales inválidas"<br>- Y registra el intento fallido para monitoreo de seguridad<br>**Reglas de negocio:**<br>-Cada sesión debe generar un token JWT válido por tiempo limitado (24 h).|EPIC-002|
|US-007|Recuperación de contraseña|	Como usuario, quiero recuperar mi cuenta de forma segura si olvido mis credenciales, para mantener el acceso protegido a mi información.|**Escenario 01: Solicitud de recuperación segura**<br>- Dado que un usuario solicita recuperar contraseña<br>- Cuando ingresa su email registrado<br>- Entonces el sistema envía enlace temporal con token de seguridad<br>- Y el enlace expira después de un tiempo limitado<br>**Escenario 02: Restablecimiento confirmado**<br>- Dado que un usuario accede al enlace de recuperación<br>- Cuando define una nueva contraseña segura<br>- Entonces el sistema actualiza las credenciales y notifica el cambio<br>- Y todas las sesiones activas se cierran automáticamente<br>**Reglas de negocio:**<br>- Los tokens de recuperación solo pueden usarse una vez.|EPIC-002|
|US-008|Gestión de sesión|Como usuario, quiero que mi sesión se maneje de forma segura, protegiendo mis datos contra accesos no autorizados por inactividad.|**Escenario 01: Cierre manual seguro**<br>- Dado que un usuario autenticado cierra sesión<br>- Cuando selecciona la opción de logout<br>- Entonces todas las tokens de acceso se invalidan<br>- Y se redirige a la página de login con confirmación<br>**Escenario 02: Protección por inactividad**<br>- Dado que un usuario permanece inactivo por 30 minutos<br>- Cuando el sistema detecta la inactividad<br>- Entonces cierra automáticamente la sesión por seguridad<br>- Y muestra mensaje informando la expiración por seguridad<br>**Reglas de negocio:**<br>- Cada usuario puede mantener máximo una sesión activa por dispositivo.<br>- Los tokens de sesión deben invalidarse al cerrar sesión o cambiar credenciales.|EPIC-002|
|US-009|Autenticación externa segura|Como usuario, quiero autenticarme mediante proveedores confiables como Google, para acceder rápidamente manteniendo estándares de seguridad.|**Escenario 01: Autenticación OAuth2 exitosa**<br>- Dado que un usuario selecciona "Iniciar con Google"<br>- Cuando completa el flujo de autorización OAuth2<br>- Entonces el sistema crea o recupera la cuenta asociada<br>- Y establece una sesión segura con los mismos privilegios<br>**Escenario 02: Manejo seguro de fallos**<br>- Dado que la autenticación externa falla<br>- Cuando el sistema recibe error del proveedor<br>- Entonces muestra mensaje genérico sin detalles técnicos<br>- Y permite intentar nuevamente o usar método alternativo<br>**Reglas de negocio:**<br>- El sistema solo debe permitir autenticación mediante proveedores externos aprobados.<br>- n caso de error en el flujo OAuth2, el sistema no debe revelar información técnica ni del proveedor. |EPIC-002|
|US-010|Cerrar sesión|Como usuario, quiero cerrar sesión de manera definitiva en todos los dispositivos, para garantizar la privacidad de mis datos al usar equipos compartidos.|**Escenario 01: Cierre de sesión global**<br>- Dado que un usuario cierra sesión manualmente<br>- Cuando confirma la acción<br>- Entonces se invalidan todos los tokens de acceso activos<br>- Y se eliminan los datos temporales del dispositivo local<br>**Escenario 02: Confirmación de cierre seguro**<br>- Dado que un usuario cierra sesión exitosamente<br>- Cuando intenta acceder a páginas protegidas<br>- Entonces el sistema redirige al login solicitando reautenticación<br>- Y no muestra información sensible en URLs o caché<br>**Reglas de negocio:**<br>- El cierre de sesión debe invalidar todos los tokens activos asociados al usuario.|EPIC-002|
|US-011|Registro simplificado de planta|Como usuario, quiero registrar una nueva planta completando información básica esencial, para tener un control centralizado de mis plantas sin complicaciones.|**Escenario 01: Registro exitoso**<br>- Dado que un usuario está en el formulario de registro de planta<br>- Cuando completa nombre, especie y ubicación (campos obligatorios)<br>- Entonces la planta se guarda automáticamente en su dashboard<br>- Y el proceso se completa en menos de 2 minutos<br>**Escenario 02: Validación de campos esenciales**<br>- Dado que un usuario deja campos obligatorios en blanco<br>- Cuando intenta guardar la planta<br>- Entonces el sistema muestra mensajes claros indicando los campos requeridos<br>- Y no permite el registro hasta completar la información mínima <br>**Reglas de negocio:**<br>-Cada planta debe estar asociada a un usuario autenticado.<br>- Los campos nombre, especie y ubicación son obligatorios para crear una planta.<br>- No se permite registrar dos plantas con el mismo nombre dentro de la misma cuenta de usuario.<br>- El sistema debe registrar automáticamente fecha de creación y última modificación.|EPIC-003|
|US-012|Edición rápida de información de planta|Como usuario, quiero editar la información básica de una planta registrada, para mantener mis datos actualizados de manera ágil.|**Escenario 01: Edición exitosa**<br>- Dado que un usuario selecciona una planta de su lista<br>- Cuando modifica información básica (nombre, especie, ubicación) y guarda<br>- Entonces los cambios se actualizan inmediatamente en el sistema<br>- Y la información modificada se refleja al instante en todas las vistas<br>**Escenario 02: Cancelación de edición**<br>- Dado que un usuario está editando una planta<br>- Cuando decide cancelar los cambios<br>- Entonces regresa a la vista anterior sin modificar la información<br>- Y los datos originales se mantienen intactos<br>**Reglas de negocio:**<br>-Solo el usuario propietario puede editar la información de una planta.<br>- Los cambios deben reflejarse de forma inmediata y persistirse en la base de datos.<br>-  No se permite guardar una edición si los campos obligatorios quedan vacíos.|EPIC-003|
|US-013|Eliminación confirmada de planta|Como usuario, quiero eliminar plantas que ya no cuido, para mantener mi lista actualizada y ordenada.|**Escenario 01: Eliminación con confirmación**<br>- Dado que un usuario selecciona eliminar una planta<br>- Cuando confirma la acción en el diálogo de verificación<br>- Entonces la planta desaparece de su lista principal<br>- Y el sistema muestra mensaje de confirmación de eliminación<br>**Escenario 02: Cancelación de eliminación**<br>- Dado que un usuario inicia el proceso de eliminación<br>- Cuando decide cancelar en el diálogo de confirmación<br>- Entonces la planta permanece en su lista sin cambios<br>- Y regresa a la vista normal de gestión de plantas <br>**Reglas de negocio:**<br>-Toda eliminación debe requerir confirmación explícita del usuario.<br>- Las alertas y registros asociados a la planta deben quedar desactivados automáticamente.<br> -No se permite eliminar una planta vinculada a sensores activos sin aviso previo.|EPIC-003|
|US-014|Configuración de parámetros básicos|Como usuario, quiero definir parámetros esenciales para cada planta, para personalizar el monitoreo según sus necesidades específicas.|**Escenario 01: Configuración de umbrales básicos**<br>- Dado que un usuario accede a la configuración de una planta<br>- Cuando define niveles de humedad mínimos y máximos recomendados<br>- Entonces los parámetros se guardan asociados al perfil de la planta<br>- Y el sistema los utiliza para generar alertas personalizadas<br>**Escenario 02: Aplicación de perfiles predefinidos**<br>- Dado que un usuario selecciona "Suculenta" como especie<br>- Cuando el sistema sugiere parámetros automáticos para esa especie<br>- Entonces el usuario puede aceptar la configuración recomendada<br>- Y los umbrales se aplican automáticamente sin configuración manual<br>**Reglas de negocio:**<br>- Cada planta debe tener configurados al menos los umbrales mínimos y máximos de humedad.<br>- Los valores de umbrales deben estar dentro de rangos válidos definidos por el sistema|EPIC-003|
|US-015|Visualización unificada de plantas|Como usuario, quiero ver todas mis plantas en una vista consolidada con estado de salud, para tener una visión rápida del estado general de mi colección.|**Escenario 01: Lista principal organizada**<br>- Dado que un usuario tiene múltiples plantas registradas<br>- Cuando accede a la sección "Mis plantas"<br>- Entonces visualiza una lista con nombre, especie, ubicación y estado de salud<br>- Y puede identificar rápidamente las plantas que necesitan atención prioritaria<br>**Escenario 02: Visualización responsive**<br>- Dado que un usuario accede desde dispositivo móvil<br>- Cuando navega por su lista de plantas<br>- Entonces la interfaz se adapta al tamaño de pantalla manteniendo legibilidad<br>- Y todas las funcionalidades principales permanecen accesibles<br>**Reglas de negocio:**<br>-Solo deben mostrarse las plantas activas del usuario autenticado.<br>- Cada planta debe mostrar su último estado de salud calculado con base en sus umbrales y mediciones recientes.<br>- El listado debe ordenarse por prioridad de atención|EPIC-003|
|US-016|Alertas esenciales de riego|Como persona ocupada, quiero recibir solo notificaciones críticas cuando mis plantas necesiten riego urgente, para actuar rápidamente sin saturación de alertas.|**Escenario 01: Alerta solo en umbral crítico**<br>- Dado que la humedad del suelo baja por debajo del nivel de emergencia<br>- Cuando el sistema detecta riesgo inminente para la planta<br>- Entonces envía una notificación push clara y urgente<br>- Y no notifica por fluctuaciones menores dentro de rangos seguros <br>**Reglas de negocio:**<br>-El sistema solo debe generar una alerta de riego cuando la humedad del suelo esté por debajo del umbral crítico configurado para la planta.<br>- No se deben enviar notificaciones por pequeñas fluctuaciones dentro del rango seguro.<br>- Si existen múltiples plantas en estado crítico, las alertas deben agruparse en una sola notificación resumen.|EPIC-004|
|US-017|Notificaciones de temperatura extrema|Como persona ocupada, quiero ser alertado solo cuando la temperatura represente peligro real para mis plantas, para evitar distracciones por variaciones normales.|**Escenario 01: Alerta por temperatura peligrosa**<br>- Dado que la temperatura supera umbrales de supervivencia de la planta<br>- Cuando la condición extrema persiste más de 15 minutos<br>- Entonces se envía alerta con acción inmediata requerida<br>- Y se suprime notificación por variaciones estacionales normales <br>**Reglas de negocio:**<br>- El sistema debe emitir alertas solo cuando la temperatura esté fuera de los umbrales de supervivencia definidos para la especie.|EPIC-004|
|US-018|Recordatorios programados simplificados|Como persona ocupada, quiero recordatorios básicos en horarios convenientes, para integrar el cuidado de plantas en mi rutina sin complicaciones.|**Escenario 01: Recordatorio en horario accesible**<br>- Dado que un usuario configura horario de recordatorio<br>- Cuando llega el momento programado en horario no laboral<br>- Entonces recibe notificación simple con lista de plantas a revisar<br>- Y la alerta no interrumpe durante horas ocupadas <br>**Reglas de negocio:**<br>- Los recordatorios deben configurarse solo en horarios definidos como “no laborales” o convenientes por el usuario.<br>- El sistema debe permitir un máximo de un recordatorio activo por planta al mismo tiempo.|EPIC-004|
|US-019|Monitoreo detallado de humedad ambiental|Como aficionado, quiero monitorear precisamente la humedad del aire, para optimizar el microclima de mis plantas especializadas.|**Escenario 01: Análisis de humedad ambiental**<br>- Dado que un sensor mide humedad ambiental fuera de rango ideal<br>- Cuando el aficionado consulta los datos detallados<br>- Entonces ve gráficos de tendencia y correlación con temperatura<br>- Y recibe recomendaciones técnicas específicas para ajustar <br>**Reglas de negocio:**<br>- Los datos anómalos o incompletos deben marcarse y excluirse del análisis gráfico|EPIC-005|
|US-020|Visualización avanzada en tiempo real|Como aficionado, quiero ver datos de sensores en tiempo real con múltiples parámetros, para realizar análisis instantáneos del estado de mis plantas.|**Escenario 01: Dashboard avanzado en tiempo real**<br>- Dado que un aficionado accede al dashboard<br>- Cuando los sensores envían datos continuamente<br>- Entonces visualiza múltiples métricas simultáneamente con actualización en segundos<br>- Y puede correlacionar humedad, temperatura y luz en una vista <br>**Reglas de negocio:**<br>-Los valores mostrados deben estar sincronizados con el timestamp más reciente disponible|EPIC-005|
|US-021|Análisis histórico con gráficos avanzados|Como aficionado, quiero analizar tendencias históricas con gráficos interactivos, para identificar patrones y mejorar mis técnicas de cuidado.|**Escenario 01: Análisis de tendencias multivariable**<br>- Dado que un aficionado selecciona rango de fechas<br>- Cuando explora los datos históricos<br>- Entonces puede superponer múltiples variables en gráficos comparativos<br>- Y identificar correlaciones entre condiciones ambientales y salud de plantas <br>**Reglas de negocio:**<br>- Los usuarios pueden consultar datos históricos dentro de un rango máximo <br> - Las consultas históricas deben optimizarse para no sobrecargar el servidor|EPIC-005|
|US-022|Reportes semanales detallados|Como aficionado, quiero recibir reportes semanales exhaustivos, para realizar seguimiento meticuloso del progreso de mis plantas.|**Escenario 01: Reporte técnico semanal**<br>- Dado que finaliza la semana<br>- Cuando el sistema genera el reporte automático<br>- Entonces incluye análisis de varianza, tendencias y comparativas<br>- Y destaca anomalías con explicaciones técnicas detalladas<br>**Reglas de negocio:**<br>- El sistema debe generar automáticamente un reporte semanal para cada usuario activo con plantas monitoreadas|EPIC-005|
|US-023|Reportes de largo plazo|Como aficionado, quiero acceder a reportes mensuales y anuales consolidados, para entender la evolución estacional de mi colección.|**Escenario 01: Análisis estacional**<br>- Dado que un aficionado solicita reporte mensual/anual<br>- Cuando el sistema procesa los datos acumulados<br>- Entonces genera análisis comparativo entre períodos<br>- Y identifica patrones estacionales y efectividad de cuidados <br>**Reglas de negocio:**<br>-Los reportes mensuales y anuales deben generarse a partir de los datos validados acumulados.<br>- El sistema debe comparar períodos consecutivos para detectar mejoras o deterioros en las condiciones.|EPIC-005|
|US-024|Exportación para análisis externo|Como aficionado, quiero exportar datos crudos en formatos analíticos, para realizar estudios avanzados con herramientas especializadas.|**Escenario 01: Exportación de datos completos**<br>- Dado que un aficionado necesita analizar datos externamente<br>- Cuando selecciona exportar dataset completo<br>- Entonces recibe archivo con todos los datos crudos y metadatos<br>- Y puede importarlo en software de análisis especializado<br>**Reglas de negocio:**<br>- Los formatos permitidos son .csv, .xlsx y .json para compatibilidad con software analítico externo|EPIC-005|
|US-025|Diagnóstico automático en alertas|Como usuario, quiero que las alertas incluyan diagnóstico automático de causas, para entender el problema raíz y aplicar la solución correcta.|**Escenario 01: Alerta con diagnóstico contextual**<br>- Dado que se detecta un problema en una planta<br>- Cuando el sistema analiza múltiples variables<br>- Entonces la alerta incluye probable causa (ej: "Posible exceso de riego por drenaje insuficiente")<br>- Y sugiere solución específica ("Reducir frecuencia de riego en 50%")<br>**Reglas de negocio:**<br>-Las recomendaciones deben estar basadas en guías validadas del sistema y no generarse sin evidencia contextual.|EPIC-005|
|US-026|	Historial de diagnósticos|Como usuario, quiero revisar el historial de alertas y diagnósticos anteriores, para aprender de patrones recurrentes y mejorar mis cuidados.|**Escenario 01: Consulta de historial diagnóstico**<br>- Dado que un usuario quiere aprender de experiencias pasadas<br>- Cuando accede al historial de alertas<br>- Entonces ve cada alerta con diagnóstico aplicado y resultado<br>- Y puede filtrar por tipo de problema o planta específica<br>**Reglas de negocio:**<br>-Cada usuario debe poder acceder solo a su propio historial de alertas y diagnósticos. <br>- El historial debe registrar fecha, diagnóstico, acción recomendada y resultado final. |EPIC-006|
|US-027|Integración automática a la comunidad|Como usuario registrado, quiero ser parte automáticamente de la comunidad según mis intereses de plantas, para comenzar a colaborar inmediatamente sin trámites adicionales.|**Escenario 01: Acceso inmediato**<br>- Dado que un usuario completa su registro en la plataforma<br>- Cuando accede por primera vez a la aplicación<br>- Entonces ya es miembro activo de la comunidad<br>- Y ve contenido personalizado según sus plantas registradas<br>**Escenario 02: Personalización por intereses**<br>- Dado que un usuario tiene plantas de especies específicas<br>- Cuando explora la comunidad<br>- Entonces encuentra grupos y discusiones relevantes a sus especies<br>- Y recibe recomendaciones de usuarios con plantas similares<br>**Reglas de negocio:**<br>-Todo usuario registrado debe ser asignado automáticamente a la comunidad al completar su perfil inicial.<br>- La categorización dentro de la comunidad debe basarse en especies de plantas registradas e intereses declarados.|EPIC 006|
|US-028|Feed comunitario|Como usuario, quiero ver un feed personalizado con publicaciones relevantes a mis plantas y nivel de experiencia, para encontrar contenido útil rápidamente.|**Escenario 01: Contenido contextual**<br>- Dado que un usuario accede al feed comunitario<br>- Cuando el sistema analiza sus plantas e historial<br>- Entonces muestra publicaciones prioritarias según sus necesidades actuales<br>- Y sugiere contenido educativo basado en sus especies<br>Escenario 02: Actualización en tiempo real<br>- Dado que un usuario está navegando el feed<br>- Cuando otros usuarios publican nuevo contenido relevante<br>- Entonces el feed se actualiza dinámicamente<br>- Y destaca publicaciones con alta interacción de la comunidad<br>**Reglas de negocio:**<br>-El contenido mostrado debe priorizar publicaciones relacionadas con especies, ubicación o temas de interés del usuario. |EPIC 006|
|US-029|	Compartir experiencias de cuidado|Como usuario, quiero compartir mis aprendizajes y técnicas exitosas de cuidado, para contribuir al conocimiento colectivo y ayudar a otros cuidadores.|**Escenario 01: Publicación de consejos estructurados**<br>- Dado que un usuario quiere compartir un consejo<br>- Cuando utiliza el formulario de publicación guiada<br>- Entonces puede categorizar por tipo de planta, problema y solución<br>- Y otros usuarios pueden aplicar fácilmente sus recomendaciones**Escenario 02: Validación comunitaria**<br>- Dado que un usuario publica un consejo<br>- Cuando otros usuarios lo aplican exitosamente<br>- Entonces recibe retroalimentación positiva y reputación<br>- Y el consejo gana visibilidad en la comunidad<br>**Reglas de negocio:**<br>-Toda publicación debe incluir al menos una categoría (tipo de planta, problema o técnica).<br>- Los usuarios pueden recibir “reconocimiento comunitario” basado en validaciones positivas.|EPIC 006|
|US-030|Compartir progreso con fotos seguras|Como usuario, quiero compartir el progreso de mis plantas mediante fotos procesadas para privacidad, para documentar evolución sin comprometer mi seguridad.|**Escenario 01: Subida segura de imágenes**<br>- Dado que un usuario selecciona una foto para compartir<br>- Cuando el sistema procesa la imagen<br>- Entonces elimina automáticamente metadatos de ubicación y dispositivo<br>- Y aplica compresión que mantiene calidad pero protege privacidad**Escenario 02: Galería de progreso**<br>- Dado que un usuario comparte múltiples fotos de una planta<br>- Cuando otros usuarios visitan su perfil<br>- Entonces pueden ver la evolución temporal organizada<br>- Y aprender del progreso documentado<br>**Reglas de negocio:**<br>- El sistema debe comprimir las imágenes garantizando equilibrio entre calidad y seguridad|EPIC 006|
|US-031|Sistema de feedback para mejorar alertas|Como usuario, quiero evaluar la utilidad de las alertas recibidas, para contribuir a que el sistema aprenda y mejore su precisión para todos.|**Escenario 01: Evaluación simple de alertas**<br>- Dado que un usuario recibe una notificación del sistema<br>- Cuando marca si fue útil o no<br>- Entonces el sistema registra el feedback anónimamente<br>- Y ajusta algoritmos para futuras alertas similares<br>**Escenario 02: Aprendizaje colectivo**<br>- Dado que múltiples usuarios evalúan alertas similares<br>- Cuando el sistema detecta patrones de feedback<br>- Entonces mejora la precisión de umbrales y timing<br>- Y reduce falsos positivos para toda la comunidad<br>**Reglas de negocio:**<br>- El feedback de los usuarios sobre alertas debe almacenarse de forma anónima y agregada. <br>- No se puede modificar ni eliminar retroalimentación una vez registrada.|EPIC 006|
|US-032|	Interacción y aprendizaje comunitario|Como usuario, quiero recibir comentarios y reacciones en mis publicaciones, para aprender de perspectivas diversas y mejorar mis técnicas.|Escenario 01: Notificaciones de interacción<br>- Dado que un usuario publica contenido en la comunidad<br>- Cuando otros usuarios comentan o reaccionan<br>- Entonces recibe notificaciones organizadas por relevancia<br>- Y puede responder fácilmente desde cualquier dispositivo**Escenario 02: Construcción de conocimiento**<br>- Dado que se genera una discusión técnica en una publicación<br>- Cuando múltiples usuarios comparten experiencias<br>- Entonces se forma un hilo de conocimiento valioso<br>- Y todos los participantes aprenden de las soluciones compartidas<br>**Reglas de negocio:**<br>- Los usuarios deben poder comentar o reaccionar únicamente en publicaciones públicas.|EPIC 006|
|US-033|Compartir en redes sociales externas|Como usuario, quiero compartir logros significativos en mis redes sociales, para inspirar a otros y documentar mis éxitos en el cuidado de plantas.|**Escenario 01: Compartir logros**<br>- Dado que un usuario tiene un logro significativo (primera flor, recuperación exitosa)<br>- Cuando selecciona compartir en redes sociales<br>- Entonces genera un post optimizado con imagen y descripción<br>- Y incluye enlace de regreso para atraer nuevos usuarios**Escenario 02: Personalización de compartido**<br>- Dado que un usuario quiere compartir contenido<br>- Cuando selecciona la plataforma destino<br>- Entonces adapta automáticamente formato y extensión<br>- Y mantiene atribución a la comunidad PlantCare<br>**Reglas de negocio:**<br>- Solo se pueden compartir publicaciones o logros propios del usuario.|EPIC 006|
|US-034|	Moderación proactiva de contenido|Como administrador, quiero mantener un ambiente seguro y constructivo en la comunidad, para garantizar que todos los usuarios tengan una experiencia positiva.|**Escenario 01: Revisión escalable de contenido**<br>- Dado que se publica nuevo contenido en la comunidad<br>- Cuando el sistema detecta posibles violaciones de normas<br>- Entonces prioriza esas publicaciones para revisión humana<br>- Y sugiere acciones basadas en historial de moderación<br>**Escenario 02: Transparencia en moderación**<br>- Dado que un administrador modera una publicación<br>- Cuando toma una acción (aprobar, editar, eliminar)<br>- Entonces registra la razón específica en logs auditables<br>- Y notifica al usuario con explicación clara cuando aplica<br>**Reglas de negocio:**<br>- Los administradores deben ser notificados de contenido reportado para validación manual.|EPIC 006|
|US-035|Protección automática de privacidad en fotos|Como usuario, quiero que todas mis fotos sean procesadas automáticamente para eliminar información sensible, para compartir libremente sin preocupaciones de seguridad.|**Escenario 01: Sanitización automática**<br>- Dado que un usuario sube cualquier foto a la plataforma<br>- Cuando el sistema procesa la imagen<br>- Entonces elimina EXIF data, ubicación GPS y metadatos del dispositivo<br>- Y aplica marca de agua discreta para protección de derechos<br>**Escenario 02: Verificación de privacidad**<br>- Dado que una foto ha sido procesada<br>- Cuando el usuario revisa la publicación<br>- Entonces puede confirmar que no contiene información sensible<br>- Y recibe explicación de las protecciones aplicadas<br>**Reglas de negocio:**<br>- El usuario debe poder verificar visualmente que su foto fue procesada antes de hacerse pública.|EPIC 006|
| US-036          | Alertas con diagnóstico integrado            | Como usuario, quiero recibir notificaciones que incluyan diagnóstico automático del problema, para entender la causa raíz y aplicar la solución correcta inmediatamente.                                                       | **Escenario 01: Diagnóstico contextual automático**<br>- Dado que se detecta humedad críticamente baja en una planta<br>- Cuando el sistema analiza variables ambientales simultáneas<br>- Entonces la alerta identifica causa probable (ej: "Temperatura alta aumentó evaporación")<br>- Y recomienda solución específica ("Regar ahora y considerar mover a sombra parcial")<br><br>**Escenario 02: Múltiples causas posibles**<br>- Dado que una planta muestra estrés por múltiples factores<br>- Cuando el sistema evalúa correlaciones<br>- Entonces prioriza las 2-3 causas más probables<br>- Y sugiere acciones para cada escenario posible <br>**Reglas de negocio:**<br>-Cada alerta debe generarse solo después de analizar al menos dos variables ambientales correlacionadas | EPIC 007                   |
| US-037          | Alertas preventivas basadas en tendencias    | Como usuario, quiero recibir advertencias tempranas cuando mis plantas muestren patrones de deterioro, para intervenir antes de que los problemas se vuelvan críticos.                                                         | **Escenario 01: Detección de tendencia negativa**<br>- Dado que una planta muestra disminución gradual en salud<br>- Cuando el sistema identifica patrón consistente por 3+ días<br>- Entonces envía alerta preventiva con análisis de tendencia<br>- Y sugiere ajustes proactivos en cuidado<br><br>**Escenario 02: Alerta de riesgo estacional**<br>- Dado que cambia la estación y las condiciones ambientales<br>- Cuando el sistema proyecta impacto en plantas específicas<br>- Entonces envía recomendaciones preventivas estacionales<br>- Y ajusta umbrales de alerta automáticamente <br>**Reglas de negocio:**<br>-El sistema debe evitar generar alertas preventivas si los datos presentan vacíos o inconsistencias. <br>- Los umbrales de alerta deben reajustarse automáticamente tras cada intervención o cambio de estación.| EPIC 007                   |
| US-038          | Alertas con soluciones escalonadas           | Como usuario, quiero que las alertas sugieran acciones inmediatas y planes a largo plazo, para resolver problemas tanto urgentes como estructurales.                                                                           | **Escenario 01: Solución inmediata + preventiva**<br>- Dado que se detecta problema de humedad recurrente<br>- Cuando se genera la alerta<br>- Entonces sugiere acción inmediata ("Regar ahora")<br>- Y recomienda solución permanente ("Considerar maceta con mejor drenaje")<br><br>**Escenario 02: Plan de acción progresivo**<br>- Dado que una planta tiene problema complejo<br>- Cuando el usuario consulta la alerta extendida<br>- Entonces muestra plan de 3 pasos con timeline<br>- Y incluye indicadores de éxito para cada etapa <br>**Reglas de negocio:**<br>- Cada alerta debe ofrecer una acción inmediata y una acción a largo plazo, claramente diferenciadas.| EPIC 007                   |
| US-039          | Alertas personalizadas por tipo de usuario   | Como usuario, quiero recibir alertas adaptadas a mi nivel de experiencia y disponibilidad, para obtener recomendaciones que pueda implementar fácilmente.                                                                      | **Escenario 01: Alertas para principiantes**<br>- Dado que un usuario tiene perfil de "principiante"<br>- Cuando se genera una alerta<br>- Entonces usa lenguaje simple y acciones básicas<br>- Y evita terminología técnica compleja<br><br>**Escenario 02: Alertas para expertos**<br>- Dado que un usuario tiene perfil de "experimentado"<br>- Cuando se genera una alerta<br>- Entonces incluye datos técnicos y opciones avanzadas<br>- Y sugiere experimentos o ajustes finos<br>**Reglas de negocio:**<br>- Las terminologías técnicas deben evitarse por completo en perfiles de principiantes.| EPIC 007                   |
| US-040          | Sistema de confirmación y seguimiento        | Como usuario, quiero confirmar cuando he aplicado las soluciones sugeridas y recibir seguimiento, para cerrar el ciclo de cuidado y mejorar el aprendizaje.                                                                    | **Escenario 01: Confirmación de acción tomada**<br>- Dado que un usuario recibe una alerta con solución<br>- Cuando marca "Acción completada"<br>- Entonces el sistema registra la intervención<br>- Y programa seguimiento automático en 24-48 horas<br><br>**Escenario 02: Seguimiento de efectividad**<br>- Dado que un usuario aplicó una solución recomendada<br>- Cuando pasa el período de seguimiento<br>- Entonces el sistema verifica si el problema se resolvió<br>- Y solicita feedback sobre la efectividad de la recomendación<br>**Reglas de negocio:**<br>-Cada alerta con acción recomendada debe permitir al usuario marcarla como “acción completada”. | EPIC 007                   |
| US-041          | Alertas con integración de conocimiento comunitario | Como usuario, quiero que las alertas incluyan soluciones validadas por la comunidad, para beneficiarme de la experiencia colectiva de otros cuidadores.                                                                       | **Escenario 01: Soluciones comunitarias validadas**<br>- Dado que se detecta un problema común<br>- Cuando se genera la alerta<br>- Entonces incluye soluciones con alta tasa de éxito reportada por la comunidad<br>- Y muestra testimonios de usuarios que resolvieron problema similar<br><br>**Escenario 02: Enlace a discusiones relevantes**<br>- Dado que un usuario quiere profundizar en un problema<br>- Cuando consulta una alerta extendida<br>- Entonces muestra enlaces a discusiones comunitarias sobre el mismo tema<br>- Y sugiere expertos en la comunidad que pueden ayudar <br>**Reglas de negocio:**<br>- Las alertas deben incluir recomendaciones con base en soluciones validadas por usuarios con alta reputación dentro de la comunidad.| EPIC 007                   |
| US-042          | Vinculación simplificada de dispositivo   | Como usuario, quiero vincular nuevos sensores IoT mediante escaneo de código QR, para comenzar a monitorear mis plantas inmediatamente sin configuración técnica compleja.                          | **Escenario 01: Registro por QR**<br>- Dado que un usuario adquiere un nuevo sensor compatible<br>- Cuando escanea el código QR del dispositivo con la app<br>- Entonces el sistema detecta automáticamente el modelo y características<br>- Y guía al usuario para asignarlo a una planta específica<br><br>**Escenario 02: Configuración automática**<br>- Dado que un usuario vincula un sensor a una planta registrada<br>- Cuando la planta tiene especie definida (ej: "Suculenta")<br>- Entonces el sistema aplica umbrales predefinidos para esa especie<br>- Y configura frecuencias de monitoreo óptimas automáticamente <br>**Reglas de negocio:**<br>- Cada dispositivo debe tener un código QR único que contenga su ID, modelo y clave de autenticación.| EPIC 008                   |
| US-043          | Configuración inteligente por perfil de planta | Como usuario, quiero que el sistema configure automáticamente los parámetros del dispositivo según el tipo de planta, para optimizar el monitoreo sin requerir conocimiento técnico.                  | **Escenario 01: Aplicación de perfiles predefinidos**<br>- Dado que un usuario selecciona "Orquídea" al registrar una planta<br>- Cuando vincula un sensor a esa planta<br>- Entonces el sistema aplica parámetros específicos para orquídeas (humedad alta, luz indirecta)<br>- Y ajusta sensibilidad de alertas según necesidades de la especie<br><br>**Escenario 02: Personalización de parámetros automáticos**<br>- Dado que un usuario tiene configuración automática activa<br>- Cuando el sistema detecta condiciones ambientales locales<br>- Entonces ajusta umbrales considerando clima y estación<br>- Y notifica al usuario sobre los ajustes aplicados <br>**Reglas de negocio:**<br>- Los perfiles predefinidos de planta deben estar almacenados en una base de conocimiento estandarizada (catálogo de especies)<br> -El sistema debe aplicar automáticamente umbrales y sensibilidades según la especie seleccionada.| EPIC 008                   |
| US-044          | Recepción de datos en tiempo real         | Como usuario, quiero ver las lecturas de mis sensores actualizarse en tiempo real, para monitorear el estado actual de mis plantas instantáneamente.                                                | **Escenario 01: Actualización continua**<br>- Dado que un dispositivo está transmitiendo datos<br>- Cuando el usuario visualiza el dashboard de una planta<br>- Entonces los valores de humedad, temperatura y luz se actualizan cada 30 segundos<br>- Y los cambios se reflejan sin necesidad de recargar manualmente<br><br>**Escenario 02: Indicadores de estado de conexión**<br>- Dado que un dispositivo está operativo<br>- Cuando el usuario revisa el estado del sensor<br>- Entonces ve indicador visual de "Conectado" y última actualización<br>- Y puede ver historial de estabilidad de conexión <br>**Reglas de negocio:**<br>-Los dispositivos deben enviar lecturas en intervalos de 30 segundos por defecto, ajustables por configuración.<br>- Si un dispositivo no envía datos durante más de 2 minutos, debe marcarse como “en riesgo de desconexión”.| EPIC 008                   |
| US-045          | Gestión proactiva de conectividad         | Como usuario, quiero ser notificado proactivamente sobre problemas de conexión del dispositivo, para mantener el monitoreo continuo de mis plantas.                                                 |**Escenario 01: Alerta de desconexión**<br>- Dado que un dispositivo vinculado pierde conexión<br>- Cuando el sistema detecta falta de comunicación por 5 minutos<br>- Entonces envía notificación push informando la desconexión<br>- Y sugiere verificar batería, WiFi o posición del dispositivo<br>**Escenario 02: Reconexión automática**<br>- Dado que un dispositivo se reconecta después de falla<br>- Cuando restablece comunicación con el servidor<br>- Entonces el sistema notifica la reconexión exitosa<br>- Y sincroniza datos acumulados durante el período offline<br>**Reglas de negocio:**<br>- Una alerta de desconexión se genera tras 5 minutos consecutivos sin comunicación con el servidor.<br> - El sistema debe intentar reconexión automática antes de emitir alerta al usuario.| EPIC 008                   |
| US-046          | Selección flexible de planes              | Como usuario, quiero elegir entre diferentes modelos de pago según mis necesidades, para acceder a las funcionalidades que mejor se adapten a mi presupuesto y nivel de uso.                        | **Escenario 01: Opción de compra única**<br>- Dado que un usuario prefiere evitar suscripciones recurrentes<br>- Cuando selecciona el plan "Básico" de pago único<br>- Entonces accede a funciones esenciales de monitoreo permanente<br>- Y no tiene compromisos de pago mensuales recurrentes<br><br>**Escenario 02: Suscripción premium**<br>- Dado que un usuario quiere funcionalidades avanzadas<br>- Cuando elige suscripción mensual o anual<br>- Entonces desbloquea inmediatamente diagnósticos avanzados e historiales extensos<br>- Y puede probar todas las funciones premium durante el período de pago <br>**Reglas de negocio:**<br>- Los planes disponibles deben estar definidos en un catálogo dinámico administrable desde backend. <br>- Los beneficios de cada plan deben actualizarse inmediatamente tras el pago o cambio.| EPIC 009                   |
| US-047          | Gestión segura de métodos de pago         | Como usuario, quiero administrar mi información de pago de forma segura, para mantener mis suscripciones activas y actualizadas.                                                                    | **Escenario 01: Actualización de tarjeta**<br>- Dado que un usuario necesita actualizar su método de pago<br>- Cuando agrega nueva tarjeta en la sección de facturación<br>- Entonces el sistema valida y tokeniza la información de forma segura<br>- Y confirma que el nuevo método está disponible para futuros cobros<br><br>**Escenario 02: Rotación segura de credenciales**<br>- Dado que un usuario reemplaza su método de pago principal<br>- Cuando el sistema procesa el cambio<br>- Entonces invalida los tokens anteriores inmediatamente<br>- Y notifica sobre la actualización exitosa <br>**Reglas de negocio:**<br>- Los datos de tarjetas deben ser tokenizados y nunca almacenados directamente por el sistema.| EPIC 009                   |
| US-048          | Cancelación flexible de suscripciones     | Como usuario, quiero poder cancelar mi suscripción en cualquier momento, para tener control total sobre mis gastos recurrentes.                                                                    | **Escenario 01: Cancelación inmediata con acceso hasta fin de período**<br>- Dado que un usuario decide cancelar su suscripción<br>- Cuando confirma la cancelación en la app<br>- Entonces el acceso premium se mantiene hasta el final del período pagado<br>- Y no se realizan cobros recurrentes adicionales<br><br>**Escenario 02: Confirmación de cancelación**<br>- Dado que un usuario completa el proceso de cancelación<br>- Cuando el sistema procesa la solicitud<br>- Entonces envía comprobante de cancelación por email<br>- Y muestra confirmación en la app con fecha de finalización <br>**Reglas de negocio:**<br>- La cancelación debe poder realizarse sin intervención del soporte técnico.<br>- Tras cancelar, el acceso premium se mantiene hasta el final del período ya pagado.| EPIC 009                   |
| US-049          | Transparencia en historial de pagos       | Como usuario, quiero consultar mi historial completo de transacciones, para tener control y registro de todos mis pagos y suscripciones.                                                            | **Escenario 01: Consulta de historial financiero**<br>- Dado que un usuario accede a su historial de pagos<br>- Cuando navega por las transacciones<br>- Entonces ve fecha, monto, método de pago y concepto de cada cargo<br>- Y puede filtrar por tipo de transacción (suscripción, compra única, etc.)<br><br>**Escenario 02: Descarga de comprobantes**<br>- Dado que un usuario necesita un comprobante específico<br>- Cuando selecciona descargar recibo de pago<br>- Entonces genera PDF con detalles completos de la transacción<br>- Y el documento incluye información fiscal requerida <br>**Reglas de negocio:**<br>-Todas las transacciones deben registrarse con número único, monto, fecha y método de pago.<br>- El historial debe conservar al menos 12 meses de registros accesibles para el usuario.| EPIC 009                   |
| US-050          | Recordatorios de renovación               | Como usuario, quiero recibir notificaciones anticipadas sobre renovaciones de suscripción, para gestionar mis finanzas proactivamente.                                                              | **Escenario 01: Alerta de renovación próxima**<br>- Dado que un usuario tiene suscripción activa<br>- Cuando faltan 3 días para la renovación automática<br>- Entonces recibe notificación push y email recordatorio<br>- Y el mensaje incluye monto a cobrar y fecha exacta<br><br>**Escenario 02: Confirmación post-renovación**<br>- Dado que se procesa una renovación de suscripción<br>- Cuando el cobro es exitoso<br>- Entonces el sistema notifica la renovación completada<br>- Y envía comprobante del nuevo período de servicio <br>**Reglas de negocio:**<br>- El sistema debe enviar notificación 3 días antes de la renovación automática.<br>- El recordatorio debe incluir monto, fecha exacta y método de pago configurado.<br>- Tras renovación exitosa, debe emitirse comprobante digital inmediato.| EPIC 009                   |

<div style="page-break-after: always;"></div>

# Historias técnicas
| Epic / Story ID | Título | Descripción | Criterios de Aceptación | Relacionado con (Epic ID) |
|-----------------|---------|-------------|--------------------------|----------------------------|
| TS-001 | Autenticación con JWT | Como desarrollador frontend, quiero autenticar usuarios mediante email y contraseña para obtener un token JWT que permita acceder a recursos protegidos. | **Escenario: Inicio de sesión exitoso**<br>Dado un usuario con credenciales válidas<br>Cuando se envía una solicitud POST /auth/login<br>Entonces el sistema responde con 200 OK y un token JWT válido.<br><br>**Escenario: Credenciales inválidas**<br>Dado un usuario con credenciales incorrectas<br>Cuando intenta iniciar sesión<br>Entonces el sistema responde con 401 Unauthorized y mensaje de error.<br><br>**Reglas:**<br>- El token expira a las 24 horas.<br>- Después de 3 intentos fallidos consecutivos, se bloquea el acceso por 15 minutos. | EPIC-002 |
| TS-002 | Registro de usuarios con validación segura | Como desarrollador frontend, quiero permitir que los usuarios se registren con validación segura, para garantizar la integridad y confidencialidad de los datos. | **Escenario: Registro exitoso**<br>Dado un usuario nuevo con datos válidos<br>Cuando envía la solicitud POST /auth/register<br>Entonces el sistema crea el usuario y responde con 201 Created.<br><br>**Escenario: Datos inválidos o incompletos**<br>Dado que el usuario omite campos requeridos<br>Cuando intenta registrarse<br>Entonces el sistema responde con 400 Bad Request y errores de validación.<br><br>**Reglas:**<br>- Contraseñas deben tener al menos 8 caracteres, una mayúscula, un número y un símbolo.<br>- El correo electrónico debe ser único y verificado. | EPIC-002 |
| TS-003 | Control de acceso basado en roles | Como desarrollador backend, quiero implementar un control de acceso por roles (usuario, administrador) para restringir el uso de endpoints sensibles. | **Escenario: Usuario autorizado**<br>Dado que un usuario tiene rol “administrador”<br>Cuando accede a un endpoint protegido<br>Entonces el sistema responde con 200 OK.<br><br>**Escenario: Usuario sin permisos**<br>Dado un usuario con rol “usuario”<br>Cuando intenta acceder a un endpoint restringido<br>Entonces el sistema responde con 403 Forbidden.<br><br>**Reglas:**<br>- Los roles deben definirse desde base de datos.<br>- El middleware valida los permisos antes de procesar la solicitud. | EPIC-002 |
| TS-004 | Interfaz de gestión de dispositivos | Como desarrollador backend, quiero implementar las operaciones CRUD para los dispositivos IoT vinculados a usuarios, para administrar su registro, edición y eliminación. | **Escenario: Registro de dispositivo**<br>Dado un usuario con cuenta activa<br>Cuando envía una solicitud con los datos del dispositivo<br>Entonces el sistema registra el dispositivo y responde con 201 Created.<br><br>**Escenario: Eliminación de dispositivo inexistente**<br>Dado un ID no registrado<br>Cuando se intenta eliminar<br>Entonces el sistema responde con 404 Not Found.<br><br>**Reglas:**<br>- Cada usuario puede registrar hasta 3 dispositivos en plan básico.<br>- El sistema valida duplicados por número de serie. | EPIC-008 |
| TS-005 | Visualización en tiempo real de sensores | Como desarrollador frontend, quiero mostrar datos de los sensores en tiempo real, para que el usuario observe el estado actual de sus plantas. | **Escenario: Datos en tiempo real disponibles**<br>Dado un dispositivo IoT activo<br>Cuando el sistema recibe lecturas de sensores<br>Entonces los valores se actualizan automáticamente en la interfaz.<br><br>**Escenario: Dispositivo desconectado**<br>Dado un sensor sin conexión<br>Cuando el usuario abre el panel<br>Entonces se muestra estado “sin conexión” y último valor registrado.<br><br>**Reglas:**<br>- Las actualizaciones deben recibirse cada 5 segundos máximo.<br>- Si no hay datos por más de 1 minuto, mostrar alerta de desconexión. | EPIC-004 |
| TS-006 | Visualización histórica de métricas | Como desarrollador frontend, quiero mostrar el historial de métricas ambientales (humedad, temperatura, luz) para cada planta. | **Escenario: Historial existente**<br>Dado que una planta tiene registros previos<br>Cuando el usuario accede al historial<br>Entonces el sistema muestra un gráfico con datos ordenados cronológicamente.<br><br>**Escenario: Sin datos históricos**<br>Dado que la planta no tiene lecturas registradas<br>Cuando el usuario accede al historial<br>Entonces se muestra mensaje “Aún no hay datos disponibles”. | EPIC-005 |
| TS-007 | Sistema de notificaciones y alertas | Como desarrollador backend, quiero generar notificaciones automáticas basadas en umbrales de humedad, temperatura o luz. | **Escenario: Alerta crítica**<br>Dado que la humedad baja por debajo del umbral definido<br>Cuando el sistema detecta la condición<br>Entonces se genera una alerta tipo “crítica” y se envía al usuario.<br><br>**Reglas:**<br>- No se envían notificaciones entre 22:00 y 07:00.<br>- Notificaciones críticas se almacenan hasta ser marcadas como leídas. | EPIC-007 |
| TS-008 | Sistema de manejo de plantas | Como desarrollador backend, quiero permitir registrar, editar, listar y eliminar plantas asociadas a cada usuario. | **Escenario: Creación exitosa**<br>Dado que un usuario envía datos válidos de una planta<br>Cuando realiza la solicitud POST /plants<br>Entonces el sistema responde con 201 Created.<br><br>**Escenario: Eliminación exitosa**<br>Dado un ID válido<br>Cuando el usuario solicita eliminar una planta<br>Entonces el sistema responde con 200 OK y mensaje de confirmación.<br><br>**Reglas:**<br>- Usuarios básicos: máximo 5 plantas.<br>- Usuarios premium: hasta 50 plantas. | EPIC-003 |
| TS-009 | Dashboard de estado de plantas | Como desarrollador frontend, quiero mostrar en un panel el estado general de las plantas, incluyendo humedad, temperatura y alertas recientes. | **Escenario: Datos disponibles**<br>Dado un usuario con plantas registradas<br>Cuando accede a su dashboard<br>Entonces visualiza todas sus plantas con su estado de salud actual.<br><br>**Escenario: Sin plantas registradas**<br>Dado un usuario nuevo<br>Cuando abre el panel<br>Entonces el sistema muestra el mensaje “No tienes plantas registradas aún”. | EPIC-003 |
| TS-010 | Comentarios en comunidad | Como desarrollador backend, quiero permitir que los usuarios publiquen, editen y eliminen comentarios en las publicaciones de la comunidad. | **Escenario: Publicación exitosa**<br>Dado que un usuario autenticado comenta en una publicación<br>Cuando envía su texto<br>Entonces el sistema guarda el comentario y responde con 201 Created.<br><br>**Reglas:**<br>- Los comentarios no pueden exceder 300 caracteres.<br>- No se permiten enlaces ni contenido ofensivo. | EPIC-006 |
| TS-011 | Reacciones y métricas comunitarias | Como desarrollador backend, quiero permitir que los usuarios reaccionen a publicaciones y que el sistema contabilice las interacciones. | **Escenario: Reacción válida**<br>Dado un usuario autenticado<br>Cuando selecciona una reacción<br>Entonces se guarda y actualiza el contador total.<br><br>**Escenario: Reacción repetida**<br>Dado un usuario que ya reaccionó<br>Cuando intenta repetir la misma acción<br>Entonces el sistema la ignora o la elimina según el diseño funcional. | EPIC-006 |
| TS-012 | Integración con API meteorológica | Como desarrollador backend, quiero integrar datos climáticos externos para mejorar las recomendaciones de cuidado de las plantas. | **Escenario: Respuesta exitosa**<br>Dado que el sistema consulta la API externa<br>Cuando recibe datos válidos<br>Entonces almacena la información y la asocia a cada planta.<br><br>**Reglas:**<br>- Consultas limitadas a 1 por hora por ubicación.<br>- Datos de clima se cachean 30 minutos. | EPIC-008 |
| TS-013 | Generación de reportes descargables | Como desarrollador frontend, quiero permitir que los usuarios descarguen reportes PDF con métricas y diagnósticos de sus plantas. | **Escenario: Reporte disponible**<br>Dado un usuario premium<br>Cuando solicita un reporte<br>Entonces el sistema genera el PDF y responde con un enlace de descarga.<br><br>**Escenario: Usuario básico**<br>Dado un usuario del plan gratuito<br>Cuando intenta generar un reporte<br>Entonces el sistema muestra mensaje de restricción. | EPIC-005 |
| TS-014 | Gestión de planes de suscripción | Como desarrollador backend, quiero implementar la lógica para registrar, actualizar o cancelar suscripciones de los usuarios. | **Escenario: Alta de suscripción**<br>Dado un usuario nuevo<br>Cuando selecciona un plan premium<br>Entonces el sistema registra la suscripción y habilita funciones avanzadas.<br><br>**Escenario: Cancelación de suscripción**<br>Dado un usuario premium<br>Cuando cancela su plan<br>Entonces el sistema mantiene los beneficios hasta el fin del período pagado. | EPIC-009 |
| TS-015 | Integración con pasarela de pago | Como desarrollador backend, quiero integrar la API de pagos para procesar cobros automáticos de suscripciones y compras únicas. | **Escenario: Pago exitoso**<br>Dado que el usuario envía datos de pago válidos<br>Cuando la pasarela confirma la transacción<br>Entonces el sistema marca la suscripción como activa y registra el comprobante.<br><br>**Escenario: Error en transacción**<br>Dado un fallo en el procesamiento del pago<br>Cuando la pasarela devuelve error<br>Entonces el sistema registra el intento fallido y notifica al usuario. | EPIC-009 |


<div style="page-break-after: always;"></div>


## 3.2. Impact Mapping.

### Segmento 1: Personas ocupadas (departamentos/oficinas)

Para el segmento de este usuario se elaboró un Impact Mapping con el objetivo de aumentar la participación activa en la plataforma y reducir la incertidumbre sobre el cuidado de las plantas. Esta herramienta nos permitió identificar los comportamientos clave que se desean promover en los usuarios, como consultar el estado de la humedad y configurar recordatorios automáticos de riego. A partir de ello, se definieron deliverables y user stories que guían el desarrollo de funcionalidades útiles y alineadas con las necesidades reales de los jóvenes universitarios que buscan mantener sus plantas sanas pese a su rutina ocupada.

**Enlace para visualizar el Impact Map en UXPressia:**
[https://uxpressia.com/w/KPfTT/i/OYO5E](https://uxpressia.com/w/KPfTT/i/OYO5E)

[![Paolo-Loayza-4.png](https://i.postimg.cc/yYZ1fn4M/Paolo-Loayza-4.png)](https://postimg.cc/qzpHqs7w)

### Segmento 2: Aficionados que cuidan varias macetas en casa

Para el segmento del usuario aficionado se elaboró un Impact Mapping con el objetivo de incrementar el control sobre el cuidado de múltiples plantas y reducir la pérdida de macetas por riego inadecuado. Esta herramienta permitió identificar los comportamientos clave que se desean promover en los usuarios, como registrar cada planta en la plataforma y consultar el historial de riego y humedad. A partir de ello, se definieron deliverables y user stories que guían el desarrollo de funcionalidades prácticas y alineadas con las necesidades reales de personas que ven en el cuidado de plantas un pasatiempo y una fuente de satisfacción personal.

**Enlace para visualizar el Impact Map en UXPressia:**
[https://uxpressia.com/w/KPfTT/i/ZTr9f](https://uxpressia.com/w/KPfTT/i/ZTr9f)

[![Luz-Ramos-4.png](https://i.postimg.cc/TPXJykff/Luz-Ramos-4.png)](https://postimg.cc/WdXkCwdH)

<div style="page-break-after: always;"></div>

## 3.3. Product Backlog.
|Orden|User Story Id|Título|Descripción|Story Points (1/2/3/5/8)|
|-----|-------------|------|-----------|------------------------|
| 1 | US-042 | Vinculación simplificada de dispositivo | Como usuario, quiero vincular nuevos sensores IoT mediante escaneo de código QR | 8 |
| 2 | US-044 | Recepción de datos en tiempo real | Como usuario, quiero ver las lecturas de mis sensores actualizarse en tiempo real | 5 |
| 3 | US-016 | Alertas esenciales de riego | Como persona ocupada, quiero recibir solo notificaciones críticas cuando mis plantas necesiten riego urgente | 5 |
| 4 | US-017 | Notificaciones de temperatura extrema | Como persona ocupada, quiero ser alertado solo cuando la temperatura represente peligro real | 3 |
| 5 | US-018 | Recordatorios programados simplificados | Como persona ocupada, quiero recordatorios básicos en horarios convenientes | 3 |
| 6 | US-025 | Diagnóstico automático en alertas | Como usuario, quiero que las alertas incluyan diagnóstico automático de causas | 5 |
| 7 | US-036 | Alertas con diagnóstico integrado | Como usuario, quiero recibir notificaciones que incluyan diagnóstico automático del problema | 8 |
| 8 | US-037 | Alertas preventivas basadas en tendencias | Como usuario, quiero recibir advertencias tempranas cuando mis plantas muestren patrones de deterioro | 8 |
| 9 | US-038 | Alertas con soluciones escalonadas | Como usuario, quiero que las alertas sugieran acciones inmediatas y planes a largo plazo | 5 |
| 10 | US-039 | Alertas personalizadas por tipo de usuario | Como usuario, quiero recibir alertas adaptadas a mi nivel de experiencia y disponibilidad | 5 |
| 11 | US-040 | Sistema de confirmación y seguimiento | Como usuario, quiero confirmar cuando he aplicado las soluciones sugeridas y recibir seguimiento | 5 |
| 12 | US-041 | Alertas con conocimiento comunitario | Como usuario, quiero que las alertas incluyan soluciones validadas por la comunidad | 5 |
| 13 | US-043 | Configuración inteligente por perfil | Como usuario, quiero que el sistema configure automáticamente los parámetros del dispositivo según el tipo de planta | 5 |
| 14 | US-045 | Gestión proactiva de conectividad | Como usuario, quiero ser notificado proactivamente sobre problemas de conexión del dispositivo | 5 |
| 15 | US-011 | Registro simplificado de planta | Como usuario, quiero registrar una nueva planta completando información básica esencial | 3 |
| 16 | US-012 | Edición rápida de información de planta | Como usuario, quiero editar la información básica de una planta registrada | 2 |
| 17 | US-013 | Eliminación confirmada de planta | Como usuario, quiero eliminar plantas que ya no cuido | 2 |
| 18 | US-014 | Configuración de parámetros básicos | Como usuario, quiero definir parámetros esenciales para cada planta | 3 |
| 19 | US-015 | Visualización unificada de plantas | Como usuario, quiero ver todas mis plantas en una vista consolidada con estado de salud | 5 |
| 20 | US-005 | Registro de usuario | Como visitante, quiero registrarme con datos básicos protegidos, para crear una cuenta segura | 5 |
| 21 | US-006 | Inicio de sesión | Como usuario registrado, quiero autenticarme de forma segura con mis credenciales | 3 |
| 22 | US-007 | Recuperación de contraseña | Como usuario, quiero recuperar mi cuenta de forma segura si olvido mis credenciales | 3 |
| 23 | US-008 | Gestión de sesión | Como usuario, quiero que mi sesión se maneje de forma segura | 2 |
| 24 | US-009 | Autenticación externa segura | Como usuario, quiero autenticarme mediante proveedores confiables como Google | 5 |
| 25 | US-010 | Cerrar sesión | Como usuario, quiero cerrar sesión de manera definitiva en todos los dispositivos | 2 |
| 26 | US-019 | Monitoreo detallado de humedad | Como aficionado, quiero monitorear precisamente la humedad del aire | 5 |
| 27 | US-020 | Visualización avanzada en tiempo real | Como aficionado, quiero ver datos de sensores en tiempo real con múltiples parámetros | 8 |
| 28 | US-021 | Análisis histórico con gráficos avanzados | Como aficionado, quiero analizar tendencias históricas con gráficos interactivos | 8 |
| 29 | US-022 | Reportes semanales detallados | Como aficionado, quiero recibir reportes semanales exhaustivos | 5 |
| 30 | US-023 | Reportes de largo plazo | Como aficionado, quiero acceder a reportes mensuales y anuales consolidados | 8 |
| 31 | US-024 | Exportación para análisis externo | Como aficionado, quiero exportar datos crudos en formatos analíticos | 5 |
| 32 | US-026 | Historial de diagnósticos | Como usuario, quiero revisar el historial de alertas y diagnósticos anteriores | 5 |
| 33 | US-001 | Acceso a la Landing Page | Como visitante, quiero acceder a una landing page optimizada desde cualquier dispositivo | 3 |
| 34 | US-002 | Secciones informativas diferenciadas | Como visitante, quiero ver secciones que muestren cómo el producto beneficia tanto a personas ocupadas como a aficionados | 3 |
| 35 | US-003 | Call to Action contextual | Como visitante, quiero encontrar botones de acción claros y contextualizados según mis intereses | 2 |
| 36 | US-004 | Testimonios segmentados | Como visitante, quiero ver testimonios de usuarios reales que representen diferentes perfiles | 3 |
| 37 | US-046 | Selección flexible de planes | Como usuario, quiero elegir entre diferentes modelos de pago según mis necesidades | 3 |
| 38 | US-047 | Gestión segura de métodos de pago | Como usuario, quiero administrar mi información de pago de forma segura | 3 |
| 39 | US-048 | Cancelación flexible de suscripciones | Como usuario, quiero poder cancelar mi suscripción en cualquier momento | 2 |
| 40 | US-049 | Transparencia en historial de pagos | Como usuario, quiero consultar mi historial completo de transacciones | 3 |
| 41 | US-050 | Recordatorios de renovación | Como usuario, quiero recibir notificaciones anticipadas sobre renovaciones de suscripción | 2 |
| 42 | US-027 | Integración automática a la comunidad | Como usuario registrado, quiero ser parte automáticamente de la comunidad según mis intereses | 3 |
| 43 | US-028 | Feed comunitario | Como usuario, quiero ver un feed personalizado con publicaciones relevantes | 5 |
| 44 | US-029 | Compartir experiencias de cuidado | Como usuario, quiero compartir mis aprendizajes y técnicas exitosas de cuidado | 3 |
| 45 | US-030 | Compartir progreso con fotos seguras | Como usuario, quiero compartir el progreso de mis plantas mediante fotos procesadas para privacidad | 5 |
| 46 | US-031 | Sistema de feedback para alertas | Como usuario, quiero evaluar la utilidad de las alertas recibidas | 3 |
| 47 | US-032 | Interacción y aprendizaje comunitario | Como usuario, quiero recibir comentarios y reacciones en mis publicaciones | 3 |
| 48 | US-033 | Compartir en redes sociales externas | Como usuario, quiero compartir logros significativos en mis redes sociales | 3 |
| 49 | US-034 | Moderación proactiva de contenido | Como administrador, quiero mantener un ambiente seguro y constructivo en la comunidad | 8 |
| 50 | US-035 | Protección automática de privacidad | Como usuario, quiero que todas mis fotos sean procesadas automáticamente para eliminar información sensible | 5 |

Link del trello: https://trello.com/invite/b/68c86d7198904c22ad495559/ATTI1228cc42e45b59fc718edf5cbbc642a2966B6FD6/1asi0572-2520-3443-plantcare
